# Generated by Django 4.1.2 on 2022-10-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('calories', models.CharField(blank=True, max_length=1000, null=True)),
                ('equivalence', models.CharField(blank=True, max_length=1000, null=True)),
                ('measure', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
