# Generated by Django 4.1.2 on 2022-10-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='letter',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
